# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cripConve.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cripConve(object):
    def setupUi(self, cripConve):
        cripConve.setObjectName("cripConve")
        cripConve.resize(1000, 613)
        cripConve.setMaximumSize(QtCore.QSize(1000, 613))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cripConve.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cripConve)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1001, 611))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("Imag1.jpg"))
        self.fondo.setObjectName("fondo")
        self.bDesplazamiento = QtWidgets.QPushButton(self.centralwidget)
        self.bDesplazamiento.setGeometry(QtCore.QRect(70, 90, 271, 61))
        self.bDesplazamiento.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bDesplazamiento.setObjectName("bDesplazamiento")
        self.bVigenere = QtWidgets.QPushButton(self.centralwidget)
        self.bVigenere.setGeometry(QtCore.QRect(670, 90, 271, 61))
        self.bVigenere.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bVigenere.setObjectName("bVigenere")
        self.bSustitucion = QtWidgets.QPushButton(self.centralwidget)
        self.bSustitucion.setGeometry(QtCore.QRect(70, 280, 271, 61))
        self.bSustitucion.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bSustitucion.setObjectName("bSustitucion")
        self.bHill = QtWidgets.QPushButton(self.centralwidget)
        self.bHill.setGeometry(QtCore.QRect(670, 280, 271, 61))
        self.bHill.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bHill.setObjectName("bHill")
        self.bAfin = QtWidgets.QPushButton(self.centralwidget)
        self.bAfin.setGeometry(QtCore.QRect(70, 470, 271, 61))
        self.bAfin.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bAfin.setObjectName("bAfin")
        self.bPermutacion = QtWidgets.QPushButton(self.centralwidget)
        self.bPermutacion.setGeometry(QtCore.QRect(670, 470, 271, 61))
        self.bPermutacion.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.bPermutacion.setObjectName("bPermutacion")
        cripConve.setCentralWidget(self.centralwidget)

        self.retranslateUi(cripConve)
        QtCore.QMetaObject.connectSlotsByName(cripConve)

    def retranslateUi(self, cripConve):
        _translate = QtCore.QCoreApplication.translate
        cripConve.setWindowTitle(_translate("cripConve", "Criptografia Convencional"))
        self.bDesplazamiento.setText(_translate("cripConve", "DESPLAZAMIENTO"))
        self.bVigenere.setText(_translate("cripConve", "VIGENÈRE"))
        self.bSustitucion.setText(_translate("cripConve", "SUSTITUCIÓN"))
        self.bHill.setText(_translate("cripConve", "HILL"))
        self.bAfin.setText(_translate("cripConve", "AFÍN"))
        self.bPermutacion.setText(_translate("cripConve", "PERMUTACIÓN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cripConve = QtWidgets.QMainWindow()
    ui = Ui_cripConve()
    ui.setupUi(cripConve)
    cripConve.show()
    sys.exit(app.exec_())
