# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cripConve.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cripConve(object):
    def setupUi(self, cripConve):
        cripConve.setObjectName("cripConve")
        cripConve.resize(1000, 613)
        cripConve.setMaximumSize(QtCore.QSize(1000, 613))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cripConve.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cripConve)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1001, 611))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("Imag1.jpg"))
        self.fondo.setObjectName("fondo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 271, 61))
        self.pushButton.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 90, 271, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 280, 271, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 280, 271, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 470, 271, 61))
        self.pushButton_5.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(670, 470, 271, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 110, 241, 21))
        self.label.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 110, 41, 21))
        self.label_2.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 300, 241, 21))
        self.label_3.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(690, 300, 241, 21))
        self.label_4.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 490, 241, 21))
        self.label_5.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(690, 490, 241, 31))
        self.label_6.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_6.setObjectName("label_6")
        cripConve.setCentralWidget(self.centralwidget)

        self.retranslateUi(cripConve)
        QtCore.QMetaObject.connectSlotsByName(cripConve)

    def retranslateUi(self, cripConve):
        _translate = QtCore.QCoreApplication.translate
        cripConve.setWindowTitle(_translate("cripConve", "Criptografia Convencional"))
        self.label.setText(_translate("cripConve", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#2dc5c8;\">DESPLAZAMIENTO</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_2.setText(_translate("cripConve", "<html><head/><body><p><span style=\" font-size:11pt; color:#2dc5c8;\">AFÍN</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("cripConve", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#2dc5c8;\">VIGENER</span></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("cripConve", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#2dc5c8;\">SUSTITUCIÓN</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_5.setText(_translate("cripConve", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#2dc5c8;\">HILL</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("cripConve", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#2dc5c8;\">PERMUTACIÓN</span></p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cripConve = QtWidgets.QMainWindow()
    ui = Ui_cripConve()
    ui.setupUi(cripConve)
    cripConve.show()
    sys.exit(app.exec_())
