# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cripDesp(object):
    def setupUi(self, cripDesp):
        cripDesp.setObjectName("cripDesp")
        cripDesp.resize(1000, 613)
        cripDesp.setMaximumSize(QtCore.QSize(1000, 613))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cripDesp.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cripDesp)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1000, 613))
        self.fondo.setStyleSheet("background-color: #ff0000;")
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("Imag1.jpg"))
        self.fondo.setScaledContents(False)
        self.fondo.setObjectName("fondo")
        self.encr = QtWidgets.QPushButton(self.centralwidget)
        self.encr.setGeometry(QtCore.QRect(300, 250, 131, 41))
        self.encr.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.encr.setObjectName("encr")
        self.encrIn = QtWidgets.QTextEdit(self.centralwidget)
        self.encrIn.setGeometry(QtCore.QRect(93, 80, 341, 151))
        self.encrIn.setObjectName("encrIn")
        self.encrOut = QtWidgets.QLabel(self.centralwidget)
        self.encrOut.setGeometry(QtCore.QRect(90, 340, 341, 151))
        self.encrOut.setStyleSheet("background-color:rgba(0,0,0,50%);\n"
"color:\'white\';")
        self.encrOut.setText("")
        self.encrOut.setObjectName("encrOut")
        self.decr = QtWidgets.QPushButton(self.centralwidget)
        self.decr.setGeometry(QtCore.QRect(760, 250, 151, 41))
        self.decr.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.decr.setObjectName("decr")
        self.decrIn = QtWidgets.QTextEdit(self.centralwidget)
        self.decrIn.setGeometry(QtCore.QRect(570, 80, 341, 151))
        self.decrIn.setObjectName("decrIn")
        self.decrOut = QtWidgets.QLabel(self.centralwidget)
        self.decrOut.setGeometry(QtCore.QRect(570, 340, 341, 151))
        self.decrOut.setStyleSheet("background-color:rgba(0,0,0,50%);\n"
"color:\'white\';")
        self.decrOut.setText("")
        self.decrOut.setObjectName("decrOut")
        self.cripAn = QtWidgets.QPushButton(self.centralwidget)
        self.cripAn.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.cripAn.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.cripAn.setObjectName("cripAn")
        self.encrSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.encrSpin.setGeometry(QtCore.QRect(90, 250, 61, 41))
        self.encrSpin.setObjectName("encrSpin")
        self.decrSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.decrSpin.setGeometry(QtCore.QRect(570, 250, 61, 41))
        self.decrSpin.setObjectName("decrSpin")
        cripDesp.setCentralWidget(self.centralwidget)

        self.retranslateUi(cripDesp)
        QtCore.QMetaObject.connectSlotsByName(cripDesp)

    def retranslateUi(self, cripConve):
        _translate = QtCore.QCoreApplication.translate
        cripConve.setWindowTitle(_translate("cripConve", "Criptografia Convencional"))
        self.encr.setText(_translate("cripConve", "ENCRIPTAR"))
        self.decr.setText(_translate("cripConve", "DESENCRIPTAR"))
        self.cripAn.setText(_translate("cripConve", "CRIPTANÁLISIS"))
