# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'despCriAn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cripDespC(object):
    def setupUi(self, cripDespC):
        cripDespC.setObjectName("cripDespC")
        cripDespC.resize(1000, 613)
        cripDespC.setMaximumSize(QtCore.QSize(1000, 613))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cripDespC.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cripDespC)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setEnabled(True)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1000, 615))
        self.fondo.setStyleSheet("background-color: #ff0000;")
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("Imag1.jpg"))
        self.fondo.setScaledContents(False)
        self.fondo.setObjectName("fondo")
        self.criAn = QtWidgets.QPushButton(self.centralwidget)
        self.criAn.setGeometry(QtCore.QRect(610, 130, 171, 41))
        self.criAn.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.criAn.setObjectName("criAn")
        self.caIn = QtWidgets.QTextEdit(self.centralwidget)
        self.caIn.setGeometry(QtCore.QRect(230, 10, 551, 101))
        self.caIn.setObjectName("caIn")
        self.caOut = QtWidgets.QLabel(self.centralwidget)
        self.caOut.setGeometry(QtCore.QRect(230, 190, 551, 421))
        self.caOut.setStyleSheet("background-color:rgba(0,0,0,50%);\n"
"color:\'white\';")
        self.caOut.setText("")
        self.caOut.setObjectName("caOut")
        self.ciDes = QtWidgets.QPushButton(self.centralwidget)
        self.ciDes.setGeometry(QtCore.QRect(20, 20, 201, 41))
        self.ciDes.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"color: #00ffff;\n"
"font: 14pt \"Berlin Sans FB\";")
        self.ciDes.setObjectName("ciDes")
        cripDespC.setCentralWidget(self.centralwidget)

        self.retranslateUi(cripDespC)
        QtCore.QMetaObject.connectSlotsByName(cripDespC)

    def retranslateUi(self, cripDespC):
        _translate = QtCore.QCoreApplication.translate
        cripDespC.setWindowTitle(_translate("cripDespC", "Criptografia Convencional"))
        self.criAn.setText(_translate("cripDespC", "CRIPTANALIZAR"))
        self.ciDes.setText(_translate("cripDespC", "CIFRADO/DESCIFRADO"))
