# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 613))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 255);")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1000, 615))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("Imag1.jpg"))
        self.fondo.setObjectName("fondo")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(70, 90, 271, 61))
        self.boton1.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.boton1.setText("")
        self.boton1.setObjectName("boton1")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(660, 90, 271, 61))
        self.boton2.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.boton2.setText("")
        self.boton2.setObjectName("boton2")
        self.boton4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4.setGeometry(QtCore.QRect(660, 440, 271, 61))
        self.boton4.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.boton4.setText("")
        self.boton4.setObjectName("boton4")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(70, 440, 271, 61))
        self.boton3.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 75 italic 12pt \"Comic Sans MS\";\n"
"")
        self.boton3.setText("")
        self.boton3.setObjectName("boton3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 110, 241, 21))
        self.label.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 460, 241, 21))
        self.label_2.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 110, 241, 21))
        self.label_3.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 460, 241, 21))
        self.label_4.setStyleSheet("background-color: rgb(21, 99, 165);\n"
"font: 8pt \"Comic Sans MS\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Criptografia"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#2dc5c8;\">CRIPTOGRAFIA CONVENCIONAL</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#2dc5c8;\">PARTE 2</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#2dc5c8;\">PARTE 3</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#2dc5c8;\">PARTE 4</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
